// This snippet file was generated by processing the source file:
// ./auth-next/manage.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_delete_user_modular]
import { deleteUser } from "https://www.gstatic.com/firebasejs/9.14.0/firebase-auth.js";
import { authService } from "../firebase.js";


export const leave = async (event) => {
    event.preventDefault();
    const user = authService.currentUser;
    if (window.confirm('정말 탈퇴하시겠습니까?')) {
        console.log('user 탈퇴');

        // They clicked Yes
        deleteUser(user).then(() => {
            // User deleted.

            console.log("유저 삭제");
            window.location.replace("");



        }).catch((error) => {
            const errorMessage = error.message;
            console.log('error:', errorMessage);
            // An error ocurred
            // ...
        });
        // [END auth_delete_user_modular]
    }
    else {
        // They clicked no
        console.log("탈퇴 취소");
    }

};
